server:
  port: 8081

# db 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: <YOUR_DB_URL>
    username: <YOUR_DB_USERNAME>
    password: <YOUR_DB_PASSWORD>
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true
    database: mysql