server:
  port: 8081

# db 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-mysql-sgp1-29526-do-user-6951745-0.b.db.ondigitalocean.com:25060/javakiosk?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: kiosk
    password: AVNS_xKYdnrrl2h1ZdXEBdCX
  thymeleaf:
    cache: false
  sql:
    init:
      platform: mysql
      # mode: always

  # spring data jpa 설정
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update # create -> 프로젝트를 실행할때마다 테이블이 다시 만들어짐
                       # update -> 바뀌는게 있을때만 변경하고 아닌 경우에는 기존 테이블 유지
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true
    database: mysql